apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
spec:
  rules:
    - host: prodlabs.luisbianconi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: giropops-senhas
                port:
                  number: 5000
  tls:
    - hosts:
        - prodlabs.luisbianconi.com
      secretName: giropops-senhas-tls

