apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default

  source:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    chart: cert-manager
    targetRevision: "1.21.0"

  helm:
    releaseName: cert-manager
  
    parameters:
      - name: installCRDs
        value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
