apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luisbianconi/giropops-gitops
    targetRevision: main
    path: apps/giropops-senhas/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

