apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luisbianconi/giropops-gitops.git
    targetRevision: main
    path: apps/giropops-senhas
  destination:
    server: https://kubernetes.default.svc
    namespace: giropops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

