apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: giropops-senhas

resources:
  - deployment-app.yaml
  - service-app.yaml
  - deployment-redis.yaml
  - service-redis.yaml
  - ingress.yaml
